PLANETS_PER_PLAYER = 8
EXTRA_PLANETS = 4

DRAG = 2
MAX_SPEED = 7

SHIP_RADIUS = 0.5

MAX_SHIP_HEALTH = 255
BASE_SHIP_HEALTH = 255
DOCKED_SHIP_REGENERATION = 0

WEAPON_COOLDOWN = 1
WEAPON_RADIUS = 5.0
WEAPON_DAMAGE = 64
EXPLOSION_RADIUS = 10.0

DOCK_RADIUS = 4
DOCK_TURNS = 5
RESOURCES_PER_RADIUS = 144
PRODUCTION_PER_SHIP = 72
BASE_PRODUCTIVITY = 6
ADDITIONAL_PRODUCTIVITY = 6

SPAWN_RADIUS = 2.0
