"""Initial database schema

Revision ID: 7f0054256cf5
Revises:
Create Date: 2017-10-03 18:16:50.116690+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f0054256cf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Autogenerated from existing database, then reformatted and fixed a few
    # things that were missed by the autogeneration. It could be further
    # cleaned up, but probably not worth it as all future changes should go in
    # new revisions.
    op.create_table(
        'badge',
        sa.Column('id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    # op.create_index('name', 'badge', ['name'], unique=True)

    op.create_table(
        'game',
        sa.Column('id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  nullable=False),
        sa.Column('replay_name', mysql.VARCHAR(length=128), nullable=False),
        sa.Column('map_width', mysql.SMALLINT(display_width=5),
                  autoincrement=False, nullable=False),
        sa.Column('map_height', mysql.SMALLINT(display_width=5),
                  autoincrement=False, nullable=False),
        sa.Column('map_seed', mysql.INTEGER(display_width=10, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('map_generator', mysql.VARCHAR(length=128), nullable=False),
        sa.Column('time_played', mysql.DATETIME(),
                  server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('replay_bucket', mysql.SMALLINT(display_width=5),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('game_time_played', 'game', ['time_played'], unique=False)

    op.create_table(
        'halite_1_user',
        sa.Column('userID', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  nullable=False),
        sa.Column('oauthID', mysql.INTEGER(display_width=12, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('oauthProvider', mysql.TINYINT(display_width=1,
                                                 unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('username', mysql.VARCHAR(length=32), nullable=False),
        sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
        sa.Column('isRunning', mysql.TINYINT(display_width=1, unsigned=True),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=False),
        sa.Column('compileStatus', mysql.TINYINT(display_width=1,
                                                 unsigned=True),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=False),
        sa.Column('organization', mysql.VARCHAR(length=64), nullable=False),
        sa.Column('language', mysql.VARCHAR(length=16), nullable=True),
        sa.Column('mu', mysql.FLOAT(), server_default=sa.text("'25'"),
                  nullable=False),
        sa.Column('sigma', mysql.FLOAT(unsigned=True),
                  server_default=sa.text("'8.333'"), nullable=False),
        sa.Column('rank', mysql.SMALLINT(display_width=5), autoincrement=False,
                  nullable=True),
        sa.Column('numSubmissions', mysql.SMALLINT(display_width=5),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=False),
        sa.Column('numGames', mysql.SMALLINT(display_width=5),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=False),
        sa.Column('creationTime', mysql.DATETIME(),
                  server_default=sa.text('CURRENT_TIMESTAMP'),
                  nullable=True),
        sa.Column('updateTime', mysql.DATETIME(), nullable=True,
                  server_default=sa.text('NULL ON UPDATE CURRENT_TIMESTAMP')),
        sa.Column('onEmailList', mysql.TINYINT(display_width=1),
                  server_default=sa.text("'1'"), autoincrement=False,
                  nullable=False),
        sa.Column('githubEmail', mysql.VARCHAR(length=64), nullable=True),
        sa.Column('verificationCode', mysql.VARCHAR(length=64), nullable=True),
        sa.Column('isEmailGood', mysql.TINYINT(display_width=1, unsigned=True),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=False),
        sa.Column('level', mysql.ENUM('High School', 'Undergraduate',
                                      'Graduate', 'Professional'),
                  server_default=sa.text("'Professional'"), nullable=False),
        sa.PrimaryKeyConstraint('userID'),
        mysql_auto_increment='5350',
        mysql_default_charset='latin1',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'organization',
        sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('organization_name', mysql.VARCHAR(length=64),
                  nullable=False),
        sa.Column('kind', mysql.ENUM('High School', 'University',
                                     'Professional School', 'Company',
                                     'Other'),
                  server_default=sa.text("'Other'"), nullable=False),
        sa.Column('verification_code', mysql.VARCHAR(length=32),
                  nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('verification_code', 'organization', ['verification_code'],
                    unique=True)

    op.create_table(
        'game_stat',
        sa.Column('game_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('turns_total', mysql.INTEGER(display_width=10,
                                               unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('planets_destroyed', mysql.INTEGER(display_width=10,
                                                     unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('ships_produced', mysql.INTEGER(display_width=10,
                                                  unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('ships_destroyed', mysql.INTEGER(display_width=10,
                                                   unsigned=True),
                  autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'],
                                name='game_stat_ibfk_1', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('game_id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_table(
        'game_view_stat',
        sa.Column('game_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('views_total', mysql.INTEGER(display_width=10,
                                               unsigned=True),
                  autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'],
                                name='game_view_stat_ibfk_1',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('game_id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_table(
        'hackathon',
        sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True),
                  nullable=False),
        sa.Column('title', mysql.VARCHAR(length=256), nullable=False),
        sa.Column('description', mysql.VARCHAR(length=4096), nullable=False),
        sa.Column('start_date', mysql.DATETIME(), nullable=False),
        sa.Column('end_date', mysql.DATETIME(), nullable=False),
        sa.Column('verification_code', mysql.VARCHAR(length=32),
                  nullable=False),
        sa.Column('organization_id', mysql.INTEGER(display_width=11),
                  autoincrement=False, nullable=True),
        sa.Column('location', mysql.VARCHAR(length=256), nullable=True),
        sa.Column('thumbnail', mysql.VARCHAR(length=512), nullable=True),
        sa.Column('is_open', mysql.TINYINT(display_width=4),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organization.id'],
                                name='hackathon_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('organization_id', 'hackathon', ['organization_id'],
                    unique=False)
    op.create_index('verification_code', 'hackathon', ['verification_code'],
                    unique=True)

    op.create_table(
        'organization_email_domain',
        sa.Column('organization_id', mysql.INTEGER(display_width=11),
                  autoincrement=False, nullable=False),
        sa.Column('domain', mysql.VARCHAR(length=64), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organization.id'],
                                name='organization_email_domain_ibfk_1'),
        sa.PrimaryKeyConstraint('organization_id', 'domain'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_table(
        'user',
        sa.Column('id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  nullable=False),
        sa.Column('oauth_id', mysql.INTEGER(display_width=12, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('oauth_provider', mysql.TINYINT(display_width=1,
                                                  unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('username', mysql.VARCHAR(length=32), nullable=False),
        sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
        sa.Column('github_email', mysql.VARCHAR(length=64), nullable=True),
        sa.Column('verification_code', mysql.VARCHAR(length=64),
                  nullable=True),
        sa.Column('is_active', mysql.TINYINT(display_width=1),
                  server_default=sa.text("'1'"), autoincrement=False,
                  nullable=False),
        sa.Column('on_email_list', mysql.TINYINT(display_width=1),
                  server_default=sa.text("'1'"), autoincrement=False,
                  nullable=False),
        sa.Column('is_email_good', mysql.TINYINT(display_width=1),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=False),
        sa.Column('player_level', mysql.ENUM('High School', 'University',
                                             'Professional'),
                  server_default=sa.text("'Professional'"), nullable=False),
        sa.Column('organization_id', mysql.INTEGER(display_width=11),
                  autoincrement=False, nullable=True),
        sa.Column('country_code', mysql.VARCHAR(length=3), nullable=True),
        sa.Column('country_subdivision_code', mysql.VARCHAR(length=10),
                  nullable=True),
        sa.Column('creation_time', mysql.DATETIME(),
                  server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('update_time', mysql.DATETIME(), nullable=True,
                  server_default=sa.text('NULL ON UPDATE CURRENT_TIMESTAMP')),
        sa.Column('api_key_hash', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('is_admin', mysql.TINYINT(display_width=1),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organization.id'],
                                name='user_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_auto_increment='1000',
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('organization_id', 'user', ['organization_id'],
                    unique=False)

    op.create_table(
        'bot',
        sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('compile_status', mysql.ENUM('Uploaded', 'InProgress',
                                               'Successful', 'Failed',
                                               'Disabled'),
                  nullable=False),
        sa.Column('compile_start', mysql.DATETIME(), nullable=True),
        sa.Column('language', mysql.VARCHAR(length=16), nullable=True),
        sa.Column('version_number', mysql.SMALLINT(display_width=5),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=False),
        sa.Column('games_played', mysql.BIGINT(display_width=20),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=False),
        sa.Column('mu', mysql.FLOAT(), server_default=sa.text("'25'"),
                  nullable=False),
        sa.Column('sigma', mysql.FLOAT(unsigned=True),
                  server_default=sa.text("'8.333'"), nullable=False),
        sa.Column('score', mysql.FLOAT(), server_default=sa.text("'0'"),
                  nullable=False),
        sa.Column('creation_time', mysql.DATETIME(),
                  server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('update_time', mysql.DATETIME(),
                  server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('timeout_sent', mysql.TINYINT(display_width=1),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='bot_ibfk_2',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_table(
        'hackathon_participant',
        sa.Column('hackathon_id', mysql.INTEGER(display_width=10,
                                                unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['hackathon_id'], ['hackathon.id'],
                                name='hackathon_participant_ibfk_4',
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                name='hackathon_participant_ibfk_3',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('hackathon_id', 'user_id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'hackathon_participant', ['user_id'],
                    unique=False)

    op.create_table(
        'user_badge',
        sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('badge_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('is_enabled', mysql.TINYINT(display_width=1),
                  server_default=sa.text("'1'"), autoincrement=False,
                  nullable=False),
        sa.Column('creation_time', mysql.DATETIME(),
                  server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('update_time', mysql.DATETIME(), nullable=True,
                  server_default=sa.text('NULL ON UPDATE CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['badge_id'], ['badge.id'],
                                name='user_badge_ibfk_2', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                name='user_badge_ibfk_1', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'badge_id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('fk_badge_id_idx', 'user_badge', ['badge_id'],
                    unique=False)

    op.create_table(
        'user_notification',
        sa.Column('id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  nullable=False),
        sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('title', mysql.VARCHAR(length=64), nullable=False),
        sa.Column('body', mysql.VARCHAR(length=2048), nullable=False),
        sa.Column('mood', mysql.ENUM('error', 'neutral', 'success'),
                  server_default=sa.text("'neutral'"), nullable=False),
        sa.Column('creation_time', mysql.DATETIME(),
                  server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                name='user_notification_ibfk_2',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'user_notification', ['user_id'], unique=False)

    op.create_table(
        'user_tier_history',
        sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('tier', mysql.VARCHAR(length=127), nullable=False),
        sa.Column('last_in_tier', mysql.DATETIME(),
                  server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('total_time_in_tier', mysql.INTEGER(display_width=10,
                                                      unsigned=True),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                name='user_tier_history_ibfk_2',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'tier'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_table(
        'bot_history',
        sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('bot_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('version_number', mysql.SMALLINT(display_width=5),
                  autoincrement=False, nullable=False),
        sa.Column('last_rank', mysql.SMALLINT(display_width=5),
                  autoincrement=False, nullable=False),
        sa.Column('last_score', mysql.FLOAT(), nullable=False),
        sa.Column('last_num_players', mysql.SMALLINT(display_width=5),
                  autoincrement=False, nullable=False),
        sa.Column('last_games_played', mysql.BIGINT(display_width=20),
                  autoincrement=False, nullable=True),
        sa.Column('language', mysql.VARCHAR(length=16), nullable=False),
        sa.Column('when_retired', mysql.DATETIME(),
                  server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['user_id', 'bot_id'], ['bot.user_id',
                                                        'bot.id'],
                                name='bot_history_ibfk_4', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                name='bot_history_ibfk_3', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'bot_id', 'version_number'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )

    op.create_table(
        'game_bot_stat',
        sa.Column('game_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('bot_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('planets_controlled', mysql.INTEGER(display_width=10,
                                                      unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('ships_produced', mysql.INTEGER(display_width=10,
                                                  unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('ships_alive', mysql.INTEGER(display_width=10,
                                               unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('ships_alive_ratio', mysql.FLOAT(), nullable=False),
        sa.Column('ships_relative_ratio', mysql.FLOAT(), nullable=False),
        sa.Column('planets_destroyed', mysql.INTEGER(display_width=10,
                                                     unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('attacks_total', mysql.INTEGER(display_width=10,
                                                 unsigned=True),
                  autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'],
                                name='game_bot_stat_ibfk_1',
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id', 'bot_id'],
                                ['bot.user_id', 'bot.id'],
                                name='fkcompid', ondelete='NO ACTION',
                                onupdate='NO ACTION'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                name='fkuserid', ondelete='NO ACTION',
                                onupdate='NO ACTION'),
        sa.PrimaryKeyConstraint('game_id', 'user_id', 'bot_id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('fkcompid_idx', 'game_bot_stat', ['user_id', 'bot_id'],
                    unique=False)

    op.create_table(
        'game_participant',
        sa.Column('game_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('bot_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('version_number', mysql.MEDIUMINT(display_width=8,
                  unsigned=True), autoincrement=False, nullable=False),
        sa.Column('log_name', mysql.VARCHAR(length=256), nullable=True),
        sa.Column('rank', mysql.SMALLINT(display_width=5, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('player_index', mysql.SMALLINT(display_width=5,
                                                 unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('timed_out', mysql.TINYINT(display_width=1),
                  autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'],
                                name='game_participant_ibfk_4',
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id', 'bot_id'],
                                ['bot.user_id', 'bot.id'],
                                name='game_participant_ibfk_3'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                name='game_participant_ibfk_2'),
        sa.PrimaryKeyConstraint('game_id', 'user_id', 'bot_id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'game_participant', ['user_id', 'bot_id'],
                    unique=False)

    op.create_table(
        'hackathon_snapshot',
        sa.Column('hackathon_id', mysql.INTEGER(display_width=10,
                                                unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('bot_id', mysql.MEDIUMINT(display_width=8, unsigned=True),
                  autoincrement=False, nullable=False),
        sa.Column('games_played', mysql.INTEGER(display_width=10,
                                                unsigned=True),
                  server_default=sa.text("'0'"), autoincrement=False,
                  nullable=True),
        sa.Column('score', mysql.FLOAT(), nullable=False),
        sa.Column('mu', mysql.FLOAT(), nullable=False),
        sa.Column('sigma', mysql.FLOAT(), nullable=False),
        sa.Column('version_number', mysql.INTEGER(display_width=11),
                  autoincrement=False, nullable=True),
        sa.Column('language', mysql.VARCHAR(length=16), nullable=True),
        sa.ForeignKeyConstraint(['hackathon_id'], ['hackathon.id'],
                                name='hackathon_snapshot_ibfk_6',
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id', 'bot_id'],
                                ['bot.user_id', 'bot.id'],
                                name='hackathon_snapshot_ibfk_5',
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                                name='hackathon_snapshot_ibfk_4',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('hackathon_id', 'user_id', 'bot_id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'hackathon_snapshot', ['user_id', 'bot_id'],
                    unique=False)


def downgrade():
    op.drop_table('hackathon_snapshot')
    op.drop_table('game_participant')
    op.drop_table('game_bot_stat')
    op.drop_table('bot_history')
    op.drop_table('user_tier_history')
    op.drop_table('user_notification')
    op.drop_table('user_badge')
    op.drop_table('hackathon_participant')
    op.drop_table('bot')
    op.drop_table('user')
    op.drop_table('organization_email_domain')
    op.drop_table('hackathon')
    op.drop_table('game_view_stat')
    op.drop_table('game_stat')
    op.drop_table('organization')
    op.drop_table('halite_1_user')
    op.drop_table('game')
    op.drop_table('badge')
