val ship_radius : float
val dock_radius : float
val max_speed : int
val max_ship_health : int
val base_ship_health : int
val weapon_cooldown : int
val weapon_radius : float
val weapon_damage : int
val explosion_radius : float
val dock_turns : int
val base_productivity : int
val spawn_radius : float
