# TODO: make this read from a JSON file instead

COMPETITION_OPEN = True
# Original PHP: "compState", "finalsPairing"
COMPETITION_FINALS_PAIRING = False

# OAuth
OAUTH_GITHUB_CONSUMER_KEY = ""
OAUTH_GITHUB_CONSUMER_SECRET = ""

# Google Cloud
GCLOUD_PROJECT = 'TODO'
GCLOUD_PROJECT_ID = 'TODO'
GCLOUD_ZONE = 'us-central1-c'

GCLOUD_COMPILATION_BUCKET = 'TODO'
GCLOUD_BOT_BUCKET = 'TODO'
GCLOUD_REPLAY_BUCKET = 'TODO'
GCLOUD_ERROR_LOG_BUCKET = 'TODO'

# Manager
HALITE_MANAGER_URL = ''

# Competition Environment (HCE)
HALITE_CE_SECRET_FOLDER = 'sosecret'

# Workers
GCLOUD_WORKER_IMAGE_FAMILY = 'TODO'
GCLOUD_WORKER_MACHINE_TYPE = 'g1-small'
