# TODO: make this read from a JSON file instead

COMPETITION_OPEN = True

# Google Cloud
GCLOUD_PROJECT = 'TODO'
GCLOUD_PROJECT_ID = 'TODO'
GCLOUD_ZONE = 'us-central1-c'

GCLOUD_COMPILATION_BUCKET = 'TODO'
GCLOUD_BOT_BUCKET = 'TODO'

# Manager
HALITE_MANAGER_URL = ''

# Workers
GCLOUD_WORKER_IMAGE_FAMILY = 'TODO'
GCLOUD_WORKER_MACHINE_TYPE = 'g1-small'
