export ADDITIONAL_PRODUCTIVITY, BASE_PRODUCTIVITY, BASE_SHIP_HEALTH, 
    DOCKED_SHIP_REGENERATION, DOCK_RADIUS, DOCK_TURNS, DRAG, EXPLOSION_RADIUS,
    EXTRA_PLANETS, INFINITE_RESOURCES, MAX_ACCELERATION, MAX_SHIP_HEALTH, MAX_SPEED,
    MAX_TURNS, PLANETS_PER_PLAYER, PRODUCTION_PER_SHIP, RESOURCES_PER_RADIUS,
    SHIPS_PER_PLAYER, SHIP_RADIUS, SPAWN_RADIUS, WEAPON_COOLDOWN, WEAPON_DAMAGE, 
    WEAPON_RADIUS

# Constants
const ADDITIONAL_PRODUCTIVITY = 6
const BASE_PRODUCTIVITY = 6
const BASE_SHIP_HEALTH = 255
const DOCKED_SHIP_REGENERATION = 0
const DOCK_RADIUS = 4.0
const DOCK_TURNS = 5
const DRAG = 7.0
const EXPLOSION_RADIUS = 10.0
const EXTRA_PLANETS = 4
const INFINITE_RESOURCES = true
const MAX_ACCELERATION = 7.0
const MAX_SHIP_HEALTH = 255
const MAX_SPEED = 7.0
const MAX_TURNS = 300
const PLANETS_PER_PLAYER = 6
const PRODUCTION_PER_SHIP = 72
const RESOURCES_PER_RADIUS = 144
const SHIPS_PER_PLAYER = 3
const SHIP_RADIUS = 0.5
const SPAWN_RADIUS = 2
const WEAPON_COOLDOWN = 1
const WEAPON_DAMAGE = 64
const WEAPON_RADIUS = 5.0