export BASE_PRODUCTIVITY, BASE_SHIP_HEALTH, DOCK_RADIUS, DOCK_TURNS, EXPLOSION_RADIUS, 
    MAX_SHIP_HEALTH, MAX_SPEED, MAX_TURNS, PRODUCTION_PER_SHIP, SHIPS_PER_PLAYER, 
    SHIP_RADIUS, SPAWN_RADIUS, WEAPON_DAMAGE, WEAPON_RADIUS

# Constants
const BASE_PRODUCTIVITY = 6
const BASE_SHIP_HEALTH = 255
const DOCK_RADIUS = 4.0
const DOCK_TURNS = 5
const EXPLOSION_RADIUS = 10.0
const MAX_SHIP_HEALTH = 255
const MAX_SPEED = 7
const MAX_TURNS = 300
const PRODUCTION_PER_SHIP = 72
const SHIPS_PER_PLAYER = 3
const SHIP_RADIUS = 0.5
const SPAWN_RADIUS = 2.0
const WEAPON_DAMAGE = 64
const WEAPON_RADIUS = 5.0