#!/usr/bin/env bash

GCLOUD_PROJECT=""
GCLOUD_ZONE=""
GCLOUD_GPU_ZONE=""

MACHINE_TYPE=""
WEBSITE_MACHINE_TYPE=""
GPU_MACHINE_TYPE=MACHINE_TYPE
IMAGE=""
GPU_IMAGE=""
WEBSITE_IMAGE=""

SERVICE_ACCOUNT=""
COORDINATOR_URL=""
SECRET_FOLDER=""