<html lang="en">
<head>
    <?php include 'includes/header.php'; ?>

    <title>TOS</title>

    <link href="lib/bootstrap.min.css" rel="stylesheet">
    <link href="style/general.css" rel="stylesheet">
    <link href="style/learn.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <?php include 'includes/navbar.php'; ?>
        <div class="row">
            <div class="col-sm-12">

                <h1>Terms of Use</h1>

                <p>Your use of the game, Halite, and the website on which these terms reside (collectively, the "Site"), and the features at this Site are subject to these Terms of Use, which we may update from time to time. <b>Please read these Terms of Use carefully before using this Site.</b> By accessing Halite, this website and any materials presented herein, or by downloading any products or materials from the Site, you agree to and are bound by the terms, conditions, policies and notices contained on this page (the "Terms"), including, but not limited to, conducting this transaction electronically, disclaimers of warranties, damage and remedy exclusions and limitations, and a choice of New York law. The Site is owned or controlled by Two Sigma Open Source, LLC and its affiliates (collectively “Two Sigma”). This Site is intended for users age thirteen or older. If you are under 13 years of age you may not use this Site.  If you are under age 18 (or the age of majority under applicable law), Two Sigma may need your parent or guardian’s consent before your use of the Site is permitted.</p>
                <p>Two Sigma reserves the right to change these Terms without notice at any time, except in accordance with applicable law. Your use of the Site after we post any changes to these Terms constitutes your agreement to those changes prospectively from the date of such changes. Any such change to these Terms shall be effective upon posting to the Site. Accordingly, you agree to periodically review these Terms when accessing or using the Site.</p>
                <p>You acknowledge and agree that Two Sigma may temporarily or permanently restrict, suspend or terminate the Terms or your access to, and use of, all or any part of the Site, with or without cause, including but not limited to any breach of these Terms as determined in Two Sigma’s sole and absolute discretion, and without prior notice or liability. Two Sigma will not be liable to you or any third party for any termination of your access to or use of the Site or any content you may have created or posted on the Site. You agree that you do not have any rights in the Site or any content that you create or post to it.</p>
                <p>Each use of the Site constitutes your agreement to be bound by and comply with the then-current Terms. If, at any time, you do not agree to be bound by or comply with these Terms, then you should cease accessing or using this Site.</p>

                <h2>1. Two Sigma Content, Limited License to Use the Site</h2>

                <p>Two Sigma owns the Site and maintains it in conjunction with its partners. All information and content contained on the Site is intended solely for the use of those persons who have been granted permission to use the Site and who have agreed to these Terms.</p>
                <p>Content on the Site that is provided by Two Sigma or its licensors, including the Halite game, graphics, images, text, software, code, screen shots, text, digitally downloadable files, trademarks, logos, service marks, product and program names, slogans, and the compilation of the foregoing, including without limitation the name or logo of Halite, Two Sigma, any of its affiliates and/or any other entity described on the Site ("Two Sigma Content") is the property of Two Sigma and its licensors, and is protected in the U.S. and internationally under trademark, copyright, and other intellectual property laws. Except as specifically permitted below, nothing contained in these Terms or the Site itself either grants or will be construed to grant to you or any third party, by implication, estoppel or otherwise, any title or interest in, or any license or right to use or reproduce Two Sigma Content contained in the Site. No act of downloading or otherwise copying Two Sigma Content from the Site will transfer title to any software or material to any user hereof. Two Sigma reserves, and may enforce to the fullest extent possible, all rights that it may have with respect to all material contained in the Site.</p>
                <p>Two Sigma grants you a limited, non-exclusive license to display and otherwise use portions of the Two Sigma Content and this Site solely for your own private, non-commercial, informational purposes only, and to print pages from the Site only in connection with that use.</p>
                <p>You agree not to download, display or use any Two Sigma Content, other than User Content (as defined herein), located on the Site for use in any publications, in public performances, on websites other than the Site for any other commercial purpose, in connection with products or services that are not those of Two Sigma, in any other manner that is likely to cause confusion among consumers, that disparages or discredits Two Sigma and/or its licensors, that dilutes the strength of Two Sigma or its licensor's property, or that otherwise infringes Two Sigma or its licensors’ intellectual property rights. You further agree to in no other way misuse any Two Sigma Content that appears on this Site.</p>
                <p>If you are a trademark or copyright owner and you believe that your trademark or copyright rights have been violated, please go to our Proprietary Rights Complaint Process and follow the instructions at that area.</p>

                <h2>2. Usage Parameters</h2>
                <p>Prohibited Uses. The following requirements apply to your use of the Site: (a) you will not use any electronic communication feature of the Site for any purpose that is unlawful, tortious, abusive, intrusive on another's privacy, harassing, libelous, defamatory, embarrassing, obscene, threatening, or hateful; (b) you will not upload, post, reproduce, or distribute any information, software, or other material protected by copyright or any other intellectual property right (as well as rights of publicity and privacy) without first obtaining the permission of the owner of such rights; (c) you will not collect or store personal data about other users; (d) you will not use the Site for any commercial purpose not expressly approved by Two Sigma in writing; (e) you will not upload, post or otherwise transmit any advertising or promotional materials or any other form of solicitation or unauthorized communication through the Site; (f) you will not upload, post, email, or otherwise transmit any material that contains viruses or any other computer code, files, or programs which might interrupt, limit, or interfere with the functionality of any computer software or hardware or telecommunications equipment; (g) you may not use the Site in any manner that could damage or overburden any Two Sigma server, or any network connected to any Two Sigma server; (h) you may not use the Site in any manner that would interfere with any other party’s use of the Site; and (i) you may not use, transfer, distribute or dispose of any information contained in the Site in any manner that could compete with the business of Two Sigma.</p>
                <p>User Content. On certain areas of our Site you will be able to submit images, text, comments, data, code, software, written posts and certain other materials ("User Content"). You understand that User Content is published on the Site for anyone to view and download and Two Sigma shall not have any liability to you for any use of a third party of your User Content. By submitting User Content, you agree that: (a) you will not post any content that is unlawful, harmful, tortious, defamatory, libelous, obscene, invasive of the privacy of another person, threatening, harassing, abusive, hateful, racist, infringing, pornographic, violent or otherwise objectionable or inappropriate as determined by Two Sigma; (b) you will not post any content that contains personal information about any individual, violates the privacy/publicity of any other individual or entity, or anything that you are under a contractual obligation to keep private or confidential; (c) you will not impersonate any person or organization, including without limitation, the personnel of Two Sigma, or misrepresent an affiliation with another person or organization; (d) you will not post any content that contains viruses, corrupted files, or any other similar software or programs that may adversely affect the operation of the Site, or feature of the Site.</p>
                <p>You further understand and agree that you have no rights to any account you may have with us, or other access to the Site or features therein and Two Sigma may cancel your account and delete all User Content submitted by you or otherwise associated with your account at any time, without notice, if Two Sigma deems that you have violated these Terms, the law, or for any other reason in Two Sigma’s sole determination. Two Sigma assumes no liability for any information, including User Content, removed from our Site, and reserves the right to permanently restrict access to the Site or a user account.</p>
                <p>By displaying, publishing, or otherwise posting any User Content on or through the Site, you hereby grant to Two Sigma, users of the Site, and any entity designated by Two Sigma, a non-exclusive, sub-licensable, worldwide, fully-paid, royalty free license to use, modify, publicly perform, publicly display, reproduce, and distribute such User Content, including but not limited to for the purposes of making the User Content available on the Site and allowing other users to view, download, modify, creative derivative works from, edit, and otherwise use User Content without time, territorial, and/or other usage limitations and without the requirement to make payment to you or to any third party or the need to seek any third party permission. This license includes the right to host, index, cache, distribute, and tag any User Content, as well as the right to sublicense User Content to third parties, including other users, for use on other media or platforms known or hereinafter developed, such as for use on mobile phones, in video or software computer programs.</p>
                <p>For clarity, you continue to retain all ownership rights in your User Content, and you continue to have the right to use your User Content in any way you choose, subject to these Terms and the license described herein. You represent and warrant that you own the content submitted, displayed, published or posted by you on the Site and otherwise have the right to grant the license set forth herein, and the displaying, publishing or posting of any content you submit, and our use thereof, and use thereof by any third party, does not and will not violate the privacy rights, publicity rights, copyrights, trademark rights, patents, contract rights or any other intellectual property rights or other rights of any person or entity.</p>
                <p>You agree to indemnify and hold Company, its parents, subsidiaries, officers, employees, licensees, customers, and website contractors and each of their officers, employees and agents, and users of the Site, harmless from any claims, damages and expenses, including reasonable attorneys' fees and costs, related to your violation of these Terms, including the Usage policies, or any violations thereof by your dependents or which arises from the use of User Content you submitted, posted, or otherwise provided to Two Sigma or this Site.</p>
                <p>Means of Access. The Site is generally intended to be viewed by a conventional Web browser. Although you may use other means to access the Site, be aware that the Site may not appear accurately through other access methods, and you use them only at your own risk. You are responsible for setting the cache settings on your browser to ensure that you are receiving the most recent data. You are responsible for obtaining and maintaining all equipment, services and other materials that you need to access and use the Site. You may not use any data mining, robots or similar data gathering and extraction programs or methods, whether automated or manual, to access, acquire, copy or monitor any portion of the Site or any data and content found on the Site, unless such devices or methods are expressly approved in advance by Two Sigma in writing.</p>
                <p>Usage Monitoring. Two Sigma reserves the right, but does not have the obligation, to access, archive, or monitor any use of this Site, or your use of this Site and your communications to the Site. Any personal information collected during such monitoring will be used in accordance with Two Sigma’s then-current Privacy Policy. By using the Site, you accept Two Sigma’s right to access, archive, and/or monitor usage to ensure service quality, or to evaluate the Site, the security of the Site, compliance with these Terms, compliance with applicable laws, rules or regulations or for any other reason. You agree that Two Sigma’s monitoring activities will not entitle you to any cause of action or other right with respect to the manner in which Two Sigma monitors your Site usage and enforces, or fails to enforce, these Terms. You further agree that in no event will Two Sigma be liable for any damages incurred by you as a result of Two Sigma’s usage monitoring.</p>
                <p>Unsolicited Ideas. Two Sigma always welcomes consumer feedback and appreciates your interest in sharing your thoughts with Two Sigma. However, it is Two Sigma’s policy not to accept or consider unsolicited ideas from outside Two Sigma, including ideas for new or improved products or packaging, technologies, product names, or promotion or marketing strategies. Should you submit an idea to Two Sigma, despite Two Sigma’s policy, Two Sigma will treat the information as non-confidential and non-proprietary and Two Sigma will be free to use the information for any purpose and will not be obligated to return or acknowledge receipt of your submitted information.</p>
                <p>Without limiting the previous paragraph, any User Content you submit to Two Sigma or the Site will not be returned to you. Accordingly, you agree that (a) Two Sigma will not treat any such submission as confidential, (b) you cannot sue Two Sigma or initiate any action against Two Sigma for use of the User Content or ideas you submit (including, but not limited to, product or advertising ideas), and (c) you understand and agree that Two Sigma may currently or in the future develop products or services that may be similar or identical to your User Content and Two Sigma does not have to pay you or anyone else if any such product or service is in any way similar to your User Content.</p>

                <h2>3. Disclaimer; No Advice</h2>

                <p>The primary mission of Two Sigma Open Source, LLC (“TSOS”) is to promote, manage and maintain open source software projects. TSOS is affiliated with Two Sigma Investments, LP, Two Sigma Advisers, LP and Two Sigma Securities, LLC, which (along with certain of their affiliates) engage in various investment advisory and broker-dealer activities. However, TSOS is not involved in the financial services businesses of these entities. Under no circumstances should any material on the site be used or considered as an offer to sell or a solicitation of an offer to buy any security, including any interest in any investment fund sponsored or managed by any Two Sigma entity, or any investment advisory services offered by any Two Sigma entity.</p>

                <h2>4. Accounts; Password Protected Areas</h2>

                <p>Portions of the Site which are password-protected may be accessed only by users who have been issued passwords by an authorized representative of Two Sigma. No one may obtain or attempt to obtain unauthorized access to such parts of the Site, or to any other protected materials or information, through any means not intentionally made available by Two Sigma for their specific use. Unauthorized individuals attempting to access, or actually accessing, these areas can be subject to criminal and/or civil prosecution.</p>
                <p>During any registration process, you must provide complete and accurate information about yourself. It is your responsibility to maintain the currency, completeness, and accuracy of your password and registration data and any loss caused by your failure to do so is your responsibility. You may not have a user name or ID that is indecent or distasteful or that we otherwise determine in our discretion is unacceptable. You are solely responsible for maintaining the confidentiality of your password and account. Additionally, you are solely responsible for any and all activities that occur under your account. You agree to notify Two Sigma immediately of any unauthorized use of your account. You further agree not to email, post, or otherwise disseminate or disclose any user name, ID, password, or other information that provides you access to the Site. Two Sigma is not liable for any loss that you may incur as a result of the unauthorized use of your password or account, either with or without your knowledge.</p>

                <h2>5. Privacy Policy</h2>

                <p>Two Sigma’s Privacy Policy posted on this website applies to use of this Site, and its terms are made a part of these Terms by this reference. Please read our <a href="privacy_policy.php">Privacy Policy</a> for more information about our information collection and use practices.</p>

                <h2>6. No Reliance</h2>

                <p>While Two Sigma uses reasonable efforts to update the information contained in the Site, Two Sigma makes no representations or warranties as to the accuracy, reliability or completeness of any information, Two Sigma Content, or User content, at or on the Site. Any content of the Site is subject to change without notice. Permission by Two Sigma to access this Site should not be construed as, or relied upon as, investment, financial, legal, regulatory, accounting, tax or similar advice. You acknowledge that any reliance on such material or systems will be at your own risk. Two Sigma makes no representations regarding the amount of time that any Two Sigma Content or User Content will be preserved.</p>
                <p>Two Sigma does not endorse, verify, evaluate or guarantee any information provided by users and nothing shall be considered as an endorsement, verification or guarantee of any User Content. You shall not create or distribute information, including but not limited to advertisements, press releases or other marketing materials, or include links to any sites which contain or suggest an endorsement by Two Sigma without the prior review and written approval of Two Sigma.</p>

                <h2>7. Materials to be Consulted in their Entirety</h2>

                <p>All materials at the Site are meant to be reviewed in their entirety, including any footnotes, legal disclaimers, restrictions, disclosures, hedge clauses and any copyright or proprietary notices, including those contained in these Terms. Any disclaimers, restrictions, disclosures or hedge clauses apply to any partial document or material in the same manner as they do the whole, and will be deemed incorporated in the portion of any material or document that you consult or download.</p>

                <h2>8. Links to Third Party Websites</h2>

                <p>Two Sigma has not reviewed any of the websites that may be linked to the Site, and is not responsible for the content of off-site pages or any other website linked or linking to this Site. Two Sigma is not responsible for the privacy practices of such other websites. Your linking to or use of any websites other than this Site is at your own risk. Two Sigma’s inclusion of links to other websites does not imply any endorsement of any kind by Two Sigma of the material located on or linked to by such websites and should not be deemed as such by any user of the Site. Two Sigma disclaims any responsibility for the products or services offered or the information contained on any websites other than the Site.</p>

                <h2>9. No Warranty</h2>

                <p>TWO SIGMA AND ITS OFFICERS, DIRECTORS, MEMBERS, PRINCIPALS, INVESTORS, AGENTS AND EMPLOYEES MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, REGARDING THe SITE, TWO SIGMA CONTENT, OR USER CONTENT AND/OR THE ACCURACY, ADEQUACY, RELIABILITY, TIMELINESS, COMPLETENESS, SUITABILITY OR OTHER CHARACTERISTICS OF THE INFORMATION AND MATERIALS CONTAINED ON OR PRESENTED THROUGH THE SITE (INCLUDING, WITHOUT LIMITATION TWO SIGMA CONTENT AND USER CONTENT). THe SITE AND ALL SUCH INFORMATION AND MATERIALS ARE PROVIDED “AS IS”, WITHOUT ANY WARRANTY OF ANY KIND, AND ON AN “AS AVAILABLE” BASIS. TWO SIGMA, TO THE FULLEST EXTENT PERMITTED BY LAW, HEREBY EXPRESSLY DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES, EXPRESS OR IMPLIED, AS TO THE SITE, TWO SIGMA CONTENT, USER CONTENT, ANY MATTER RELATED TO THE SITE AND SUCH INFORMATION AND MATERIALS ON THE SITE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT AND AVAILABILITY. TWO SIGMA EXPRESSLY DISCLAIMS LIABILITY FOR ERRORS AND OMISSIONS IN THE SITE OR THE INFORMATION AND MATERIALS CONTAINED THEREIN.</p>
                <p>You acknowledge that you are aware that by using this Site, as with any other website on the Internet, you may be subject to security and privacy exploitations, including, eavesdropping, sniffing, spoofing, hacking, breaking passwords, harassment, exposure to objectionable material, posturing, and/or other security or privacy hazards.</p>
                <p>TWO SIGMA AND ITS OFFICERS, DIRECTORS, MEMBERS, PRINCIPALS, INVESTORS, AGENTS AND EMPLOYEES FURTHER ASSUME NO RESPONSIBILITY FOR, AND MAKE NO WARRANTIES THAT, INFORMATION, SERVICES OR FUNCTIONS CONTAINED AT THe SITE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITE OR THE SERVER THAT MAKES IT AVAILABLE WILL BE FREE OF VIRUSES, WORMS, “TROJAN HORSES” OR OTHER HARMFUL COMPONENTS. TWO SIGMA AND ITS OFFICERS, DIRECTORS, MEMBERS, PRINCIPALS, INVESTORS, AGENTS AND EMPLOYEES SHALL NOT BE LIABLE FOR ANY DAMAGES OF ANY TYPE OR KIND TO YOUR COMPUTER, VIRUSES THAT MAY INFECT YOUR COMPUTER, OR SERVICES REPAIRS OR CORRECTIONS THAT MUST BE PERFORMED ON YOUR COMPUTER OR OTHER PROPERTY ON ACCOUNT OF YOUR ACCESS OR USE OF THE SITE.</p>

                <h2>10. Limitation of Liability; Indemnification</h2>

                <p>IN NO EVENT SHALL TWO SIGMA OR ITS OFFICERS, DIRECTORS, MEMBERS, PRINCIPALS, INVESTORS, CLIENTS, AGENTS OR EMPLOYEES BE LIABLE FOR ANY CLAIMS, LIABILITIES, LOSSES, COSTS OR DAMAGES OF ANY KIND, INCLUDING DIRECT, INDIRECT, PUNITIVE, EXEMPLARY, INCIDENTAL, SPECIAL, LOST PROFITS OR CONSEQUENTIAL DAMAGES, ARISING OUT OF OR IN ANY WAY CONNECTED WITH (I) THE USE OF OR INABILITY TO ACCESS AND/OR USE THE SITE OR WITH ANY DELAY IN USING THE SITE, INCLUDING BUT NOT LIMITED TO LOSS OF REVENUE, TRADING, PROFITS, ANTICIPATED PROFITS, BUSINESS, SAVINGS, GOODWILL, USE, OPPORTUNITY OR DATA; (II) TWO SIGMA CONTENT, USER CONTENT, OR ANY OTHER INFORMATION AND MATERIALS CONTAINED ON OR OBTAINED THROUGH THE SITE; OR (III) OTHERWISE ARISING OUT OF THE ACCESS TO AND/OR USE OF THE SITE. NOR SHALL TWO SIGMA OR ITS OFFICERS, DIRECTORS, MEMBERS, PRINCIPALS, INVESTORS, CLIENTS, AGENTS OR EMPLOYEES BE RESPONSIBLE FOR ANY DAMAGES WHATSOEVER THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES, ERRORS, DEFECTS, DELAYS IN OPERATION OR TRANSMISSION, OR ANY FAILURE OF PERFORMANCE WHETHER OR NOT CAUSED BY EVENTS BEYOND TWO SIGMA’S REASONABLE CONTROL, INCLUDING BUT NOT LIMITED TO ACTS OF GOD, COMMUNICATIONS LINE FAILURE, THEFT, DESTRUCTION, OR UNAUTHORIZED ACCESS TO THIS SITE'S RECORDS, PROGRAMS, OR SERVICES IN ANY CASE WHETHER BASED ON THEORIES ARISING IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE), STRICT LIABILITY OR OTHERWISE. THE FOREGOING LIMITATIONS APPLY EVEN IF TWO SIGMA OR ANY OF ITS OFFICERS, DIRECTORS, MEMBERS, PRINCIPALS, INVESTORS, CLIENTS, AGENTS OR EMPLOYEES HAVE BEEN ADVISED OF THE POSSIBILITY OF DAMAGES OR COULD HAVE FORESEEN THE DAMAGES. FURTHER, NONE OF TWO SIGMA OR ANY OF ITS OFFICERS, DIRECTORS, MEMBERS, PRINCIPALS, INVESTORS, CLIENTS, AGENTS OR EMPLOYEES WILL BE RESPONSIBLE FOR ANY FAILURE TO COMPLY, BY YOU OR ANY THIRD PARTY, WITH THESE TERMS OR WITH APPLICABLE FEDERAL, STATE AND/OR LOCAL LAWS. SOME JURISDICTIONS LIMIT THE EXCLUSION OF DAMAGES OR LIMITATION OF LIABILITY, SO THE ABOVE EXCLUSIONS AND LIMITATIONS MAY NOT APPLY TO YOU. IF ANY PART OF THE EXCLUSIONS OR DAMAGES OR LIMITATION OF LIABILITY SET FORTH ABOVE IS UNENFORCEABLE UNDER APPLICABLE LAW, THE AGGREGATE LIABILITY OF TWO SIGMA OR ITS OFFICERS, DIRECTORS, MEMBERS, PRINCIPALS, INVESTORS, AGENTS AND EMPLOYEES WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY SUCH LAW. IN NO EVENT SHALL TWO SIGMA’S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION (WHETHER IN CONTRACT OR TORT, INCLUDING BUT NOT LIMITED TO, NEGLIGENCE) EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING THIS SITE OR $50, WHICHEVER AMOUNT IS LOWER.</p>
                <p>These limitations of liability will apply regardless of: (i) any negligence or gross negligence of Two Sigma or any of its officers, directors, members, principals, investors, clients, agents or employees or (ii) whether the liability arises in negligence, gross negligence, strict liability, contract, tort (including negligence or gross negligence) or any other theory of legal liability; and will remain in effect even if any remedy fails of its essential purpose.</p>
                <p>Your sole remedy for dissatisfaction with your use of the Site is to stop using the Site.</p>
                <p>You hereby agree, at your own expense, to indemnify, defend and hold Two Sigma and its officers, directors, members, principals, investors, agents and employees harmless from and against any and all liability costs incurred by these parties in connection with any claim arising out of any breach by you of these Terms or any of the representations, warranties and covenants made by you herein, including, without limitation, attorneys’ fees and costs. You shall cooperate as fully as reasonably required or requested in the defense of any such claim. Two Sigma reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you and you shall not in any event settle any matter without the written consent of Two Sigma.</p>

                <h2>11. General</h2>

                <p>Both you and Two Sigma acknowledge and agree that no partnership is formed and neither of you nor Two Sigma has the power or the authority to obligate or bind the other.</p>
                <p>These Terms are governed by the internal laws of the State of New York, without reference to its conflicts of laws provisions. You consent to the jurisdiction of, and venue shall lie in, any federal or state court located in the Borough of Manhattan, New York City as the exclusive jurisdiction and venue for the adjudication of all disputes arising out of or relating to the use of the Site.  You further irrevocably and unconditionally waive your right to a jury trial for any claim or cause of action arising out of or relating to the use of the Site. You hereby appoint the Secretary of State of the State of New York as your agent for service of process in any such proceeding. These Terms operate to the fullest extent permissible by law.</p>
                <p>Any notice to Two Sigma shall be given in writing and sent by registered mail to Two Sigma Open Source, LLC, 100 Avenue of the Americas, 16th Floor, New York, NY 10013, Attention: Halite TOU Matters, or at such successor address as designated by Two Sigma in its sole discretion from time to time.</p>
                <p>The failure of Two Sigma to comply with these Terms because of an act of God, war, fire, riot, terrorism, earthquake, actions of federal, state or local governmental authorities or for any other reason beyond the reasonable control of Two Sigma, shall not be deemed a breach of these Terms.</p>
                <p>If Two Sigma fails to act with respect to your breach or anyone else's breach on any occasion, Two Sigma is not waiving its right to act with respect to future or similar breaches.</p>
                <p>If any provision of these Terms is held to be invalid or unenforceable in any jurisdiction, such provision shall be deemed modified to the minimum extent necessary so that such provision shall no longer be held to be invalid or unenforceable, and these Terms shall be interpreted so as to achieve the intent expressed herein to the greatest extent possible in the jurisdiction in question. Any such modification, invalidity or unenforceability shall be strictly limited both to such provision and to such jurisdiction.</p>
                <p>This website is not an offer to, or solicitation of, any potential clients or investors for the provision by Two Sigma of investment management, advisory or any other related services. No material listed on this website is or should be construed as investment advice, nor is anything on this website an offer to sell, or a solicitation of an offer to buy, any security or other instrument. Links from this website to third-party websites do not imply any endorsement by the third party of this website or of the link; nor do they imply any endorsement by this firm of the third-party website or of the link</p>

                <hr>

                <p>Last Updated November 2, 2016</p>

                <p>© 2016 Two Sigma Open Source, LLC. ALL RIGHTS RESERVED.</p>


            </div>
        </div>
        <?php include 'includes/footer.php'; ?>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="script/backend.js"></script>
    <script src="script/general.js"></script>
</body>
</html>
